PFM-2843--Organization module changes
egovernments/works-mdms-data pull request #415
Opened 2023-04-18 13:00 UTC by Vasanth26-egov

2023-04-19 04:56 UTC, jagankumar-egov requested changes

2023-04-19 04:56 UTC, jagankumar-egov commented on data/state1/works/OrganisationClassification.json
Not required

2023-04-19 04:56 UTC, jagankumar-egov commented on data/state1/works/OrganisationType.json
Not required in UI

2023-04-19 05:01 UTC, Vasanth26-egov commented on data/state1/works/OrganisationClassification.json
Deleted

2023-04-19 05:01 UTC, Vasanth26-egov commented on data/state1/works/OrganisationType.json
Deleted

2023-04-20 07:34 UTC, jagankumar-egov approved these changes

2023-04-20 07:40 UTC, jagankumar-egov approved these changes

2023-04-20 07:40 UTC, merged